### ISSUE TITLE
segmentation fault while running main.cpp

### ISSUE THREAD

**Issue by msdeep14** [Bug-Assassins/DFC_query_builder#3]
I'm getting segmentation fault when executing a.out for main.cpp

stack trace:
Starting program: /home/mandeep/DFC/Core/a.out 

Program received signal SIGSEGV, Segmentation fault.
__GI_____strtol_l_internal (nptr=0x0, endptr=endptr@entry=0x0, 
    base=base@entry=10, group=group@entry=0, 
    loc=0x7ffff78af500 <_nl_global_locale>) at ../stdlib/strtol_l.c:297
297 ../stdlib/strtol_l.c: No such file or directory.

**Comment by ashish1294** [comment]
Could you tell me the exact command you used to compile the program?

Include a screenshot if possible.

**Comment by msdeep14** [comment]
![seg_error](https://cloud.githubusercontent.com/assets/11789072/18239220/6ad67190-7361-11e6-996f-cb9a4f4d6b09.png)

Also, in the main program when I replaced
  int port = atoi(argv[1]);
with
 int port = atoi(argv[0]);

there was no segmentation fault, but 
if(SERVER_OUTPUT)
    {
        printf("Running Server on Port No : %d\n\n", port);
        fflush(stdout);
    }
the if() condition fails.

I'm using apache2 

another issue:
the index.php is not executing as per the screenshot provided by you in your repo.

Here is the screenshot:
![query](https://cloud.githubusercontent.com/assets/11789072/18239490/4881546e-7363-11e6-870d-11752a68438d.jpg)

**Comment by ashish1294** [comment]
SERVER_OUTPUT is pre - processing directive defined in "declarations.h".
The default value is set to 0. So the if condition fails.

If you want to change that configuration then change that value to 1 and
then recompile. The if condition will pass.

**Comment by ashish1294** [comment]
Regarding second issue - I think you misplaced a <?php ?> opening statement
somewhere because of which you are getting this wrong rendering.

**Comment by msdeep14** [comment]
screenshot for the second issue
can you please help me out
![php_error](https://cloud.githubusercontent.com/assets/11789072/18327930/5a14f45c-756a-11e6-98f8-a8e95c60caf1.png)

**Comment by msdeep14** [comment]
well thanks and second issue is resolved.

But first issue gives segmentation fault.
This line in main.cpp 
 int port = atoi(argv[1]);
if I make it
 int port = atoi(argv[0]);
programs runs succesfully but no connection is established.
![conn](https://cloud.githubusercontent.com/assets/11789072/18328934/f0981e1e-756e-11e6-8289-81107e6f805c.png)

**Comment by ajithps** [comment]
Since you said you want to start your own project from scratch (In the mail) which was similar to this, I would suggest you to look into what argv is and in this context what argv[1] should hold. Looking into what atoi function does will also help. That should be enough to solve the server issue(It isn't an issue btw). What you have done will actually break things. 
Google the things that I mentioned and you should be able to resolve it :)

**Comment by msdeep14** [comment]
I appreciate your help @ashish1294 @ajithps 
Thanks :)

**Comment by ashish1294** [comment]
We should use command line flags instead of command line arguments here. Or
at least use some existing argument parser which throws appropriate error
when command line flag is not passed.

Another thing here is that the port number is really an optional argument.
We should ideally choose a port number at random and display it when
argv[1] is not provided.

Additionally, a repo's readme should ideally have the instruction to run
the binary.

There are a lot of such small issues with project and we do not have the
required bandwidth to fix them ! Sorry !
